# Generated by Django 5.2.1 on 2025-06-12 12:28

import cors.models.user_models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('kalit', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='TOKEN')),
                ('mobile', models.CharField(max_length=15)),
                ('is_expired', models.BooleanField(default=False)),
                ('tries', models.SmallIntegerField(default=0)),
                ('extra', models.JSONField(default='{}')),
                ('is_verified', models.BooleanField(default=False)),
                ('step', models.CharField(choices=[('regis', 'Registration'), ('send', 'OTP send'), ('conf_regis', 'Registration'), ('login', 'Login'), ('send_login', 'OTP send'), ('conf_login', 'Loggen in')], max_length=56)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ful_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Isim Sharif')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('user_date', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'user'), (2, 'admin')], default=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', cors.models.user_models.CustomUserManager()),
            ],
        ),
    ]
