# Generated by Django 5.2.1 on 2025-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0005_product_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
